spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

swagger:
  openapi:
    dev-url: http://localhost:8080
    prod-url: https://curriculo-api.henriquebarucco.com.br
    
curriculo:
    data: https://henriquebarucco.github.io/Curriculo-API/data.json
    api: ${API_URL}
    token: ${TOKEN}
    token_ip: ${TOKEN_IP}
    telefone: ${TELEFONE}

springdoc:
    swagger-ui:
        disable-swagger-default-url: true
        path: "/"

server:
  error:
    include-stacktrace: never